### ISSUE TITLE
Purecounter Vanilla JS cdn not working

### ISSUE THREAD

**Issue by Toba-O** [srexi/purecounterjs#30] opened 2022-01-31 17:50 UTC
https://cdn.jsdelivr.net/npm/@srexi/purecounterjs/dist/purecounter_vanilla.js

Not working on my website and on codepen?

**Comment by srexi** [comment] 2022-01-31 18:09
Probably duplicate of #29 

Can you share your codepen please

**Comment by srexi** [comment] 2022-02-01 09:02
Try this: https://cdn.jsdelivr.net/npm/@srexi/purecounterjs@1.4.1/dist/purecounter_vanilla.js

**Comment by Toba-O** [comment] 2022-02-02 14:07
Sorry, yes it is a duplicate of #29 

Here is a codepen: 
https://codepen.io/pen?template=VwraNVG

**Comment by rzlnhd** [comment] 2022-02-04 11:40
@Toba-O you need to initialize PureCounter manualy. Just add ```new PureCounter()``` on your JavaScript file, or you can store it on a Variable like ```var pure = new PureCounter()```, and it will work. Read [Initialize PureCounter](https://github.com/srexi/purecounterjs#1-initialize-purecounter) for more information.

![image](https://user-images.githubusercontent.com/43670693/152522521-89f91258-c6c6-4428-930f-6e2700a4b446.png)

**Comment by Toba-O** [comment] 2022-02-09 15:08
Thanks -that worked

This can be closed

**Closed as completed** 2022-02-09 15:09 UTC
